Country="Russia"
zip_code_valid="43085"
zip_code_novalid="0"
region_novalid = '1'
region_valid = '1'
country_valid = '1'
country_novalid = '1'
state=""
reg_email_valid="admin12312@mail.ru"
reg_email_invalid = 'qwe'
email_valid="kaxihor976@hagendes.com"
email_novalid="qwerty"
password_valid="fertertewrtert234513245@asds!!!"
password_invalid="qwe"
First_Name="Ivan"
Last_Name="Ivanov"
card_number=""
data=""
cvv=""
product=""
address=""
Region=""
postal_Code=""
city=""
Phone=""
mmyy=""
name_card=""
shipping_address=""